all:
  vars:
    ansible_httpapi_use_proxy: false
  children:
    cisco_xrd:
      vars:
        ansible_user: clab
        ansible_password: clab@123
      hosts:
        clab-ospf2-xrd1: {}
        clab-ospf2-xrd2: {}
        clab-ospf2-xrd3: {}
        clab-ospf2-xrd4: {}
    juniper_vjunosrouter:
      vars:
        ansible_user: admin
        ansible_password: admin@123
      hosts:
        clab-ospf2-vmx1: {}
        clab-ospf2-vmx2: {}
