---
interfaces:
  - name: Loopback0
    description: RouterID
    ipv4_address: "100.2.0.2/32"
  - name: Loopback1
    description: MPLS_VPN_LOOPBACK
    ipv4_address: "100.2.1.2/32"
  - name: GigabitEthernet2
    description: to_xrd4_Gi0/0/0/3
    ipv4_address: "12.4.2.2/30"
  - name: GigabitEthernet3
    description: to_c8000v1_Gi3
    ipv4_address: "12.1.2.2/30"

ospf:
  process_id: 1
  router_id: "100.2.0.2"
  areas:
    - id: "0.0.0.2"
      interfaces:
        - name: Loopback0
          network: "100.2.0.2"
          wildcard: "0.0.0.0"
        - name: Loopback1
          network: "100.2.1.2"
          wildcard: "0.0.0.0"
        - name: GigabitEthernet2
          network: "12.4.2.0"
          wildcard: "0.0.0.3"
        - name: GigabitEthernet3
          network: "12.1.2.0"
          wildcard: "0.0.0.3"
