---
interfaces:
  - name: Loopback0
    description: RouterID
    ipv4_address: "100.1.0.1/32"
  - name: Loopback1
    description: MPLS_VPN_LOOPBACK
    ipv4_address: "100.1.1.1/32"
  - name: Ethernet1
    description: to_xrd1_Gi0/0/0/3
    ipv4_address: "11.1.1.2/30"
  - name: Ethernet2
    description: to_ceos2_eth2
    ipv4_address: "11.1.2.1/30"
  - name: Ethernet3
    description: to_ceos3_eth1
    ipv4_address: "11.1.3.1/30"

ospf:
  process_id: 1
  router_id: "100.1.0.1"
  areas:
    - id: "0.0.0.1"
      interfaces:
        - name: Loopback0
          prefix: "100.1.0.1/32"
        - name: Loopback1
          prefix: "100.1.1.1/32"
        - name: Ethernet1
          prefix: "11.1.1.0/30"
        - name: Ethernet2
          prefix: "11.1.2.0/30"
        - name: Ethernet3
          prefix: "11.1.3.0/30"
